[build]
builder = "DOCKERFILE"

[[services]]
name = "api"
dockerfilePath = "apps/api/Dockerfile"

[[services]]
name = "web"
dockerfilePath = "apps/web/Dockerfile"

[[services]]
name = "admin"
dockerfilePath = "apps/admin/Dockerfile"
